sky:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNGvnqQGSwz66NQeFwu
    access-key-secret: 0QbZSPr1RJSzDobEbaKTkkIBdM3FSA
    bucket-name: take-abc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxb6b80d02bb3184b8
    secret: 38d2c71e3bc568040e6b6da41b70080f


